### ISSUE TITLE
Detekt command is not working on Mac

### ISSUE THREAD

**Issue by recaldev** [Architect-Coders/MU8#22]
```java
> Task :data:detekt FAILED
java.lang.IllegalArgumentException: Must consist of two parts for Unix OSs or three for Windows (report-id:path).
    at io.gitlab.arturbosch.detekt.cli.ReportPath$Companion.from(ReportPath.kt:22)
    at io.gitlab.arturbosch.detekt.cli.CliArgs$reportPaths$2.invoke(CliArgs.kt:180)
    at io.gitlab.arturbosch.detekt.cli.CliArgs$reportPaths$2.invoke(CliArgs.kt:12)
    at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
    at io.gitlab.arturbosch.detekt.cli.CliArgs.getReportPaths(CliArgs.kt)
    at io.gitlab.arturbosch.detekt.cli.OutputFacade.<init>(OutputFacade.kt:20)
    at io.gitlab.arturbosch.detekt.cli.runners.Runner.execute(Runner.kt:24)
    at io.gitlab.arturbosch.detekt.cli.Main.main(Main.kt:16)
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':data:detekt'.
> Process 'command '/Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java'' finished with non-zero exit value 1
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
```

**Comment by recaldev** [comment]
Not going to work on this at the moment.
